# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'm18homework' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for m18homework
  pod 'SnapKit', '~> 5.0.0'
  pod 'Alamofire', '~> 5.4'

end
